import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
Obsidian Task Center — energy-aware task board + CLI
Built with esbuild.
*/`;

const prod = process.argv[2] === "production";
const nodeBuiltins = [...builtinModules, ...builtinModules.map((name) => `node:${name}`)];

const cssBanner = `/*
 * Obsidian Task Center — assembled stylesheet.
 * GENERATED: do not edit this file directly. Source lives in src/styles/*.css,
 * imported in order by src/styles/index.css and bundled here by esbuild.
 */`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeBuiltins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

// CSS: Obsidian only loads the single plugin-root `styles.css`, and runtime
// @import of sibling files is unreliable. So we author styles in src/styles/*
// and bundle them (resolving @import) back into the root `styles.css`.
const cssContext = await esbuild.context({
  banner: { css: cssBanner },
  entryPoints: ["src/styles/index.css"],
  bundle: true,
  loader: { ".css": "css" },
  logLevel: "info",
  outfile: "styles.css",
  // Keep the shipped stylesheet readable (and diffable against the source);
  // CSS minification saves little next to the JS bundle. esbuild still resolves
  // @import and concatenates the modules into one root-level styles.css.
  minify: false,
});

if (prod) {
  await Promise.all([context.rebuild(), cssContext.rebuild()]);
  await Promise.all([context.dispose(), cssContext.dispose()]);
  process.exit(0);
} else {
  await Promise.all([context.watch(), cssContext.watch()]);
}
